import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { openDb, id, settings } from './db.js';
import { satang, baht, thaiDateTime, dayRange, splitMinutes, thaiDay, tripProfit } from './domain.js';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
for(const line of (fs.existsSync(path.join(root,'.env'))?fs.readFileSync(path.join(root,'.env'),'utf8'):'').split(/\r?\n/)) {
  const m=line.match(/^([A-Z0-9_]+)=(.*)$/); if(m&&!process.env[m[1]]) process.env[m[1]]=m[2];
}
const db=openDb();
const origin=process.env.APP_ORIGIN || 'http://localhost:3000';
const production=!/^https?:\/\/localhost(?::\d+)?$/.test(origin);
const demo=process.env.DEMO_MODE==='true' && !production;
if(production&&(!process.env.SESSION_SECRET||process.env.SESSION_SECRET.length<32))throw Error('Set a SESSION_SECRET of at least 32 characters');
const cookieName='grab_session';
const hash=x=>crypto.createHmac('sha256',process.env.SESSION_SECRET||'local-development-only-secret').update(x).digest('hex');
const json=(res,status,data)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(JSON.stringify(data));};
const err=(status,message)=>Object.assign(new Error(message),{status});
const string=(v,max=250)=>{if(typeof v!=='string'||v.length>max)throw err(400,'ข้อความไม่ถูกต้องหรือยาวเกินไป');return v.trim();};
const num=(v,max=1e8)=>{const n=Number(v);if(!Number.isFinite(n)||n<0||n>max)throw err(400,'ตัวเลขไม่ถูกต้อง');return n;};
const money=(v,positive=false)=>{let n;try{n=satang(v)}catch(e){throw err(400,e.message)}if(positive&&n<0)throw err(400,'จำนวนเงินต้องไม่ติดลบ');return n;};
const when=v=>{try{return thaiDateTime(v)}catch(e){throw err(400,e.message)}};
const readBody=async(req,limit=2_000_000)=>{let chunks=[],size=0;for await(const c of req){size+=c.length;if(size>limit)throw err(413,'ไฟล์หรือข้อมูลใหญ่เกินไป');chunks.push(c)}return Buffer.concat(chunks)};
const body=async req=>{try{return JSON.parse((await readBody(req)).toString('utf8')||'{}')}catch(e){if(e.status)throw e;throw err(400,'JSON ไม่ถูกต้อง')}};
const auth=req=>{const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.split('=')[1];if(!raw)return null;const row=db.prepare('SELECT u.*,s.expires_at FROM auth_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=?').get(hash(raw));if(!row||Date.parse(row.expires_at)<=Date.now())return null;return row};
const makeSession=(res,userId)=>{const token=crypto.randomBytes(32).toString('base64url');const expires=new Date(Date.now()+22*86400000);db.prepare('INSERT INTO auth_sessions(token_hash,user_id,expires_at) VALUES(?,?,?)').run(hash(token),userId,expires.toISOString());res.setHeader('Set-Cookie',`${cookieName}=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${22*86400}${production?'; Secure':''}`)};
const requireUser=req=>{const u=auth(req);if(!u)throw err(401,'กรุณาเข้าสู่ระบบ');return u};
const owner=(table,userId,key)=>{const row=db.prepare(`SELECT * FROM ${table} WHERE id=? AND user_id=?`).get(key,userId);if(!row)throw err(404,'ไม่พบรายการ');return row};
const dateFilter=(url,column='occurred_at')=>{const from=url.searchParams.get('from'),to=url.searchParams.get('to');if(from&&to){const [a]=dayRange(from),[,b]=dayRange(to);return {clause:` AND ${column}>=? AND ${column}<?`,params:[a,b]}}return {clause:'',params:[]}};
function serialize(type,row){const x={...row};if(type==='trips'){for(const k of ['gross','tip','toll','platform_fee']){x[k+'_baht']=baht(x[k+'_satang']);delete x[k+'_satang']}}if(type==='fuel_logs'){x.total_baht=baht(x.total_satang);delete x.total_satang}if(type==='wallet_entries'||type==='operating_costs'){x.amount_baht=baht(x.amount_satang);delete x.amount_satang}return x}
const tables={
  sessions:{table:'driving_sessions',date:'start_at',fields:b=>{const start_at=when(b.start_at),end_at=when(b.end_at);splitMinutes(start_at,end_at);return {start_at,end_at,note:string(b.note||'',500)}}},
  trips:{table:'trips',date:'started_at',fields:b=>{const started_at=when(b.started_at),ended_at=when(b.ended_at);if(ended_at<started_at)throw err(400,'เวลาสิ้นสุดก่อนเวลาเริ่ม');const payment_method=string(b.payment_method||'credit',10);if(!['credit','cash'].includes(payment_method))throw err(400,'ช่องทางชำระไม่ถูกต้อง');return {started_at,ended_at,service:string(b.service||'GrabCar',60),pickup:string(b.pickup||'',200),dropoff:string(b.dropoff||'',200),paid_km:num(b.paid_km||0),deadhead_km:num(b.deadhead_km||0),gross_satang:money(b.gross_baht||0,true),tip_satang:money(b.tip_baht||0,true),toll_satang:money(b.toll_baht||0,true),platform_fee_satang:money(b.platform_fee_baht||0,true),payment_method,note:string(b.note||'',500)}}},
  fuel:{table:'fuel_logs',date:'filled_at',fields:b=>({filled_at:when(b.filled_at),liters:num(b.liters),total_satang:money(b.total_baht,true),odometer_km:b.odometer_km===''||b.odometer_km==null?null:num(b.odometer_km),station:string(b.station||'',150),source:'manual',external_id:null,note:string(b.note||'',500)})},
  wallet:{table:'wallet_entries',date:'occurred_at',fields:b=>{const wallet=string(b.wallet,10);if(!['credit','cash'].includes(wallet))throw err(400,'กระเป๋าไม่ถูกต้อง');const amount_satang=money(b.amount_baht);if(!amount_satang)throw err(400,'จำนวนเงินต้องไม่เป็นศูนย์');const trip_id=b.trip_id||null;if(trip_id)owner('trips',b.userId,trip_id);return {occurred_at:when(b.occurred_at),wallet,kind:string(b.kind||'adjustment',50),amount_satang,note:string(b.note||'',500),trip_id}}},
  costs:{table:'operating_costs',date:'occurred_at',fields:b=>({occurred_at:when(b.occurred_at),category:string(b.category,80),amount_satang:money(b.amount_baht,true),note:string(b.note||'',500)})}
};
function syncTripWallet(user,trip){db.prepare("DELETE FROM wallet_entries WHERE user_id=? AND trip_id=? AND kind IN ('trip','platform_fee')").run(user.id,trip.id);const wallet=trip.payment_method;const received=Number(trip.gross_satang)+Number(trip.tip_satang)-(wallet==='credit'?Number(trip.platform_fee_satang):0);if(received)db.prepare('INSERT INTO wallet_entries(id,user_id,occurred_at,wallet,kind,amount_satang,note,trip_id) VALUES(?,?,?,?,?,?,?,?)').run(id(),user.id,trip.ended_at,wallet,'trip',received,'รับจากงานวิ่ง',trip.id);if(wallet==='cash'&&Number(trip.platform_fee_satang))db.prepare('INSERT INTO wallet_entries(id,user_id,occurred_at,wallet,kind,amount_satang,note,trip_id) VALUES(?,?,?,?,?,?,?,?)').run(id(),user.id,trip.ended_at,'credit','platform_fee',-Number(trip.platform_fee_satang),'ค่าธรรมเนียมงานเงินสด',trip.id)}
function writeRecord(type,user,b,key){const t=tables[type];if(!t)throw err(404,'ไม่พบประเภทข้อมูล');const fields=t.fields({...b,userId:user.id});if(type==='fuel'&&!fields.liters)throw err(400,'ลิตรต้องมากกว่าศูนย์');db.exec('BEGIN');try{if(key){owner(t.table,user.id,key);const cols=Object.keys(fields);db.prepare(`UPDATE ${t.table} SET ${cols.map(c=>c+'=?').join(',')} WHERE id=? AND user_id=?`).run(...Object.values(fields),key,user.id)}else{key=id();const cols=Object.keys(fields);db.prepare(`INSERT INTO ${t.table}(id,user_id,${cols.join(',')}) VALUES(?, ?, ${cols.map(()=>'?').join(',')})`).run(key,user.id,...Object.values(fields))}const record=owner(t.table,user.id,key);if(type==='trips')syncTripWallet(user,record);db.exec('COMMIT');return serialize(t.table,record)}catch(e){db.exec('ROLLBACK');throw e}}
function analytics(user,url){const from=url.searchParams.get('from')||thaiDay(new Date(Date.now()-29*86400000).toISOString()),to=url.searchParams.get('to')||thaiDay(new Date().toISOString());const [a]=dayRange(from),[,b]=dayRange(to);const trips=db.prepare('SELECT * FROM trips WHERE user_id=? AND started_at>=? AND started_at<? ORDER BY started_at').all(user.id,a,b);const fuel=db.prepare('SELECT * FROM fuel_logs WHERE user_id=? AND filled_at>=? AND filled_at<? ORDER BY filled_at').all(user.id,a,b);const costs=db.prepare('SELECT * FROM operating_costs WHERE user_id=? AND occurred_at>=? AND occurred_at<?').all(user.id,a,b);const sessions=db.prepare('SELECT * FROM driving_sessions WHERE user_id=? AND end_at>? AND start_at<?').all(user.id,a,b);const wallet=db.prepare('SELECT wallet,SUM(amount_satang) balance FROM wallet_entries WHERE user_id=? GROUP BY wallet').all(user.id);const prior=db.prepare('SELECT * FROM fuel_logs WHERE user_id=? AND odometer_km IS NOT NULL ORDER BY filled_at').all(user.id);let kmPerLiter=null;for(let i=prior.length-1;i>0;i--){const km=prior[i].odometer_km-prior[i-1].odometer_km;if(km>0&&prior[i].liters>0){kmPerLiter=km/prior[i].liters;break}}const fuelPerKm=kmPerLiter&&fuel.length?Math.round(fuel.reduce((s,x)=>s+Number(x.total_satang),0)/fuel.reduce((s,x)=>s+x.liters,0)/kmPerLiter):0;const days={};const add=(day,field,n)=>{days[day]??={day,trips:0,revenue_satang:0,profit_satang:0,minutes:0};days[day][field]+=n};for(const s of sessions)for(const p of splitMinutes(s.start_at,s.end_at))if(p.day>=from&&p.day<=to)add(p.day,'minutes',p.minutes);let paid=0,dead=0,revenue=0,profit=0;for(const t of trips){const p=tripProfit(t,fuelPerKm),d=thaiDay(t.started_at);add(d,'trips',1);add(d,'revenue_satang',p.revenue_satang);add(d,'profit_satang',p.profit_satang);paid+=t.paid_km;dead+=t.deadhead_km;revenue+=p.revenue_satang;profit+=p.profit_satang}const fuelCost=fuel.reduce((s,x)=>s+Number(x.total_satang),0),operatingCost=costs.reduce((s,x)=>s+Number(x.amount_satang),0);return {from,to,tripCount:trips.length,paidKm:paid,deadheadKm:dead,deadheadRatio:(paid+dead)?dead/(paid+dead):0,revenueBaht:baht(revenue),tripProfitEstimateBaht:baht(profit),fuelCostBaht:baht(fuelCost),operatingCostBaht:baht(operatingCost),netCashEstimateBaht:baht(revenue-fuelCost-operatingCost),kmPerLiter,drivingHours:sessions.reduce((sum,s)=>sum+splitMinutes(s.start_at,s.end_at).reduce((n,x)=>n+x.minutes,0),0)/60,walletBalances:Object.fromEntries(wallet.map(x=>[x.wallet,baht(x.balance)])),daily:Object.values(days).sort((x,y)=>x.day.localeCompare(y.day)).map(x=>({...x,revenueBaht:baht(x.revenue_satang),profitBaht:baht(x.profit_satang)}))}}
async function googleCallback(req,res,url){const code=url.searchParams.get('code'),state=url.searchParams.get('state');const cookie=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('oauth_state='))?.split('=')[1];if(!code||!state||!cookie||!crypto.timingSafeEqual(Buffer.from(hash(state)),Buffer.from(hash(cookie))))throw err(400,'OAuth state ไม่ถูกต้อง');const params=new URLSearchParams({code,client_id:process.env.GOOGLE_CLIENT_ID,client_secret:process.env.GOOGLE_CLIENT_SECRET,redirect_uri:process.env.GOOGLE_REDIRECT_URI||origin+'/api/auth/google/callback',grant_type:'authorization_code'});const tokenRes=await fetch('https://oauth2.googleapis.com/token',{method:'POST',body:params});if(!tokenRes.ok)throw err(502,'Google token exchange ไม่สำเร็จ');const token=await tokenRes.json();const infoRes=await fetch('https://openidconnect.googleapis.com/v1/userinfo',{headers:{Authorization:`Bearer ${token.access_token}`}});if(!infoRes.ok)throw err(502,'Google profile ไม่สำเร็จ');const info=await infoRes.json();if(!info.email_verified||!info.sub||!info.email)throw err(403,'บัญชี Google ยังไม่ยืนยันอีเมล');if(process.env.GOOGLE_ALLOWED_EMAIL&&info.email.toLowerCase()!==process.env.GOOGLE_ALLOWED_EMAIL.toLowerCase())throw err(403,'บัญชีนี้ไม่ได้รับอนุญาต');let user=db.prepare('SELECT * FROM users WHERE google_sub=?').get(info.sub);if(!user){const existing=db.prepare('SELECT * FROM users WHERE email=?').get(info.email);if(existing){db.prepare('UPDATE users SET google_sub=?,name=?,avatar_url=? WHERE id=?').run(info.sub,info.name||info.email,info.picture||null,existing.id);user=existing}else{user={id:id()};db.prepare('INSERT INTO users(id,email,name,avatar_url,google_sub) VALUES(?,?,?,?,?)').run(user.id,info.email,info.name||info.email,info.picture||null,info.sub)}}makeSession(res,user.id);res.setHeader('Set-Cookie',[res.getHeader('Set-Cookie'),'oauth_state=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0']);res.writeHead(302,{Location:'/'});res.end()}
async function ocrUpload(req,user){const raw=await readBody(req,5_000_000);let input;try{input=JSON.parse(raw.toString())}catch{throw err(400,'JSON ไม่ถูกต้อง')}const match=String(input.image||'').match(/^data:image\/(png|jpeg|webp);base64,([A-Za-z0-9+/=]+)$/);if(!match)throw err(400,'รองรับภาพ PNG, JPEG, WebP');const bytes=Buffer.from(match[2],'base64');if(bytes.length>4_000_000)throw err(413,'ภาพใหญ่เกิน 4 MB');const folder=path.join(root,'uploads');fs.mkdirSync(folder,{recursive:true});const draftId=id(),filename=path.join(folder,draftId+'.'+(match[1]==='jpeg'?'jpg':match[1]));fs.writeFileSync(filename,bytes,{flag:'wx'});let text='';if(process.env.GOOGLE_VISION_API_KEY){const r=await fetch('https://vision.googleapis.com/v1/images:annotate?key='+encodeURIComponent(process.env.GOOGLE_VISION_API_KEY),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({requests:[{image:{content:match[2]},features:[{type:'TEXT_DETECTION'}]}]})});if(r.ok){const out=await r.json();text=out.responses?.[0]?.fullTextAnnotation?.text||''}}const moneyMatch=text.match(/(?:ยอดรวม|รายได้|ค่าโดยสาร|total|fare)\s*[:฿]?\s*([\d,]+(?:\.\d{1,2})?)/i);const parsed={gross_baht:moneyMatch?moneyMatch[1].replaceAll(',',''):'',raw_text:text};db.prepare('INSERT INTO ocr_drafts(id,user_id,image_path,raw_text,parsed_json) VALUES(?,?,?,?,?)').run(draftId,user.id,filename,text,JSON.stringify(parsed));return {id:draftId,status:'pending',...parsed,ocrAvailable:!!process.env.GOOGLE_VISION_API_KEY}}
async function lineWebhook(req){if(!process.env.LINE_CHANNEL_SECRET)throw err(503,'ยังไม่ได้ตั้งค่า LINE');const raw=await readBody(req);const expected=crypto.createHmac('sha256',process.env.LINE_CHANNEL_SECRET).update(raw).digest('base64');const actual=req.headers['x-line-signature']||'';if(actual.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(actual),Buffer.from(expected)))throw err(401,'LINE signature ไม่ถูกต้อง');const data=JSON.parse(raw.toString());for(const event of data.events||[]){if(!event.webhookEventId)continue;const account=db.prepare("SELECT user_id FROM settings WHERE key='line_user_id' AND value=?").get(event.source?.userId||'');const inserted=db.prepare('INSERT OR IGNORE INTO integration_events(id,source,external_id,user_id) VALUES(?,?,?,?)').run(id(),'line',event.webhookEventId,account?.user_id||null);if(!inserted.changes)continue;if(event.type==='message'&&event.message?.type==='text'&&account){const msg=event.message.text.slice(0,1000);if(/^เติมน้ำมัน\s/i.test(msg)){const m=msg.match(/^เติมน้ำมัน\s+(\d+(?:\.\d+)?)\s+(\d+(?:\.\d{1,2})?)(?:\s+(\d+(?:\.\d+)?))?/);if(m){db.prepare('INSERT INTO fuel_logs(id,user_id,filled_at,liters,total_satang,odometer_km,source,note) VALUES(?,?,?,?,?,?,?,?)').run(id(),account.user_id,new Date(event.timestamp).toISOString(),Number(m[1]),money(m[2],true),m[3]?Number(m[3]):null,'line','บันทึกผ่าน LINE')}}}}return {ok:true}}
async function flowtrackSync(user){if(!process.env.FLOWTRACK_BASE_URL||!process.env.FLOWTRACK_API_KEY)throw err(503,'ยังไม่ได้ตั้งค่า FlowTrack');const base=new URL(process.env.FLOWTRACK_BASE_URL);if(base.protocol!=='https:')throw err(400,'FlowTrack ต้องใช้ HTTPS');const target=new URL(process.env.FLOWTRACK_FUEL_PATH||'/api/fuel',base);if(target.origin!==base.origin)throw err(400,'FlowTrack URL ไม่ถูกต้อง');const r=await fetch(target,{headers:{Authorization:`Bearer ${process.env.FLOWTRACK_API_KEY}`,'Accept':'application/json'},signal:AbortSignal.timeout(15000)});if(!r.ok)throw err(502,'FlowTrack ตอบกลับไม่สำเร็จ');const data=await r.json();if(!Array.isArray(data))throw err(502,'รูปแบบข้อมูล FlowTrack ไม่ถูกต้อง');let added=0;for(const x of data.slice(0,500)){if(!x.id)continue;const result=db.prepare('INSERT OR IGNORE INTO fuel_logs(id,user_id,filled_at,liters,total_satang,odometer_km,station,source,external_id,note) VALUES(?,?,?,?,?,?,?,?,?,?)').run(id(),user.id,when(x.filled_at),num(x.liters),money(x.total_baht,true),x.odometer_km==null?null:num(x.odometer_km),string(x.station||'',150),'flowtrack',string(String(x.id),120),'');added+=Number(result.changes)}return {added,total:data.length}}
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
async function handler(req,res){const url=new URL(req.url,origin),p=url.pathname,method=req.method||'GET';try{
  res.setHeader('X-Frame-Options','DENY');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('Content-Security-Policy',"default-src 'self'; img-src 'self' data: https://lh3.googleusercontent.com; style-src 'self'; script-src 'self'; connect-src 'self'; base-uri 'self'; form-action 'self'");
  if(p.startsWith('/api/')&&method!=='GET'&&p!=='/api/integrations/line/webhook'){const incoming=req.headers.origin;if(incoming&&incoming!==origin)throw err(403,'Origin ไม่ถูกต้อง')}
  if(p==='/api/health')return json(res,200,{ok:true});
  if(p==='/api/auth/google'&&method==='GET'){if(!process.env.GOOGLE_CLIENT_ID||!process.env.GOOGLE_CLIENT_SECRET)throw err(503,'ยังไม่ได้ตั้งค่า Google Login');const state=crypto.randomBytes(24).toString('base64url');res.setHeader('Set-Cookie',`oauth_state=${state}; HttpOnly; SameSite=Lax; Path=/; Max-Age=600${production?'; Secure':''}`);const target=new URL('https://accounts.google.com/o/oauth2/v2/auth');target.search=new URLSearchParams({client_id:process.env.GOOGLE_CLIENT_ID,redirect_uri:process.env.GOOGLE_REDIRECT_URI||origin+'/api/auth/google/callback',response_type:'code',scope:'openid email profile',state,prompt:'select_account'});res.writeHead(302,{Location:target.href});return res.end()}
  if(p==='/api/auth/google/callback'&&method==='GET')return await googleCallback(req,res,url);
  if(p==='/api/auth/demo'&&method==='POST'){if(!demo)throw err(404,'ไม่พบหน้า');const u=db.prepare("SELECT * FROM users WHERE email='demo@local.test'").get();makeSession(res,u.id);return json(res,200,{ok:true})}
  if(p==='/api/auth/logout'&&method==='POST'){const raw=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(cookieName+'='))?.split('=')[1];if(raw)db.prepare('DELETE FROM auth_sessions WHERE token_hash=?').run(hash(raw));res.setHeader('Set-Cookie',`${cookieName}=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0`);return json(res,200,{ok:true})}
  if(p==='/api/integrations/line/webhook'&&method==='POST')return json(res,200,await lineWebhook(req));
  if(p.startsWith('/api/')){const user=requireUser(req);
    if(p==='/api/me')return json(res,200,{id:user.id,name:user.name,email:user.email,avatar:user.avatar_url,demo});
    if(p==='/api/analytics')return json(res,200,analytics(user,url));
    if(p==='/api/calendar'){const month=url.searchParams.get('month')||thaiDay(new Date().toISOString()).slice(0,7);if(!/^\d{4}-\d\d$/.test(month))throw err(400,'เดือนไม่ถูกต้อง');const from=month+'-01',to=new Date(Date.parse(from+'T00:00:00+07:00')+35*86400000).toISOString().slice(0,10);return json(res,200,analytics(user,new URL(`/api/analytics?from=${from}&to=${to}`,origin)).daily)}
    if(p==='/api/settings'){if(method==='GET')return json(res,200,settings(db,user.id));if(method==='PUT'){const b=await body(req);for(const key of ['vehicle','fuel_type','line_user_id','monthly_target_baht'])if(key in b)db.prepare('INSERT INTO settings(user_id,key,value) VALUES(?,?,?) ON CONFLICT(user_id,key) DO UPDATE SET value=excluded.value').run(user.id,key,string(String(b[key]),200));return json(res,200,settings(db,user.id))}}
    if(p==='/api/integrations/status')return json(res,200,{google:!!process.env.GOOGLE_CLIENT_ID,line:!!process.env.LINE_CHANNEL_SECRET,flowtrack:!!process.env.FLOWTRACK_BASE_URL,ocr:!!process.env.GOOGLE_VISION_API_KEY});
    if(p==='/api/integrations/flowtrack/sync'&&method==='POST')return json(res,200,await flowtrackSync(user));
    if(p==='/api/ocr/drafts'&&method==='GET')return json(res,200,db.prepare('SELECT id,created_at,status,raw_text,parsed_json FROM ocr_drafts WHERE user_id=? ORDER BY created_at DESC LIMIT 50').all(user.id).map(x=>({...x,parsed:JSON.parse(x.parsed_json)})));
    if(p==='/api/ocr/drafts'&&method==='POST')return json(res,201,await ocrUpload(req,user));
    const draft=p.match(/^\/api\/ocr\/drafts\/([^/]+)\/(confirm|discard)$/);if(draft&&method==='POST'){const d=owner('ocr_drafts',user.id,draft[1]);if(d.status!=='pending')throw err(409,'ร่างนี้ดำเนินการแล้ว');if(draft[2]==='discard'){db.prepare("UPDATE ocr_drafts SET status='discarded' WHERE id=?").run(d.id);return json(res,200,{ok:true})}const trip=writeRecord('trips',user,await body(req));db.prepare("UPDATE ocr_drafts SET status='confirmed' WHERE id=?").run(d.id);return json(res,200,trip)}
    const m=p.match(/^\/api\/(sessions|trips|fuel|wallet|costs)(?:\/([^/]+))?$/);if(m){const [_,type,key]=m,t=tables[type];if(method==='GET'&&!key){const f=dateFilter(url,t.date);const rows=db.prepare(`SELECT * FROM ${t.table} WHERE user_id=?${f.clause} ORDER BY ${t.date} DESC LIMIT 500`).all(user.id,...f.params);return json(res,200,rows.map(x=>serialize(t.table,x)))}if(method==='POST'&&!key)return json(res,201,writeRecord(type,user,await body(req)));if(method==='PUT'&&key)return json(res,200,writeRecord(type,user,await body(req),key));if(method==='DELETE'&&key){owner(t.table,user.id,key);db.exec('BEGIN');try{if(type==='trips')db.prepare('DELETE FROM wallet_entries WHERE user_id=? AND trip_id=?').run(user.id,key);db.prepare(`DELETE FROM ${t.table} WHERE id=? AND user_id=?`).run(key,user.id);db.exec('COMMIT')}catch(e){db.exec('ROLLBACK');throw e}return json(res,200,{ok:true})}}
    throw err(404,'ไม่พบ API');
  }
  if(method!=='GET')throw err(405,'ไม่รองรับวิธีนี้');const rel=p==='/'?'index.html':p.slice(1);if(!['index.html','app.js','styles.css','favicon.svg'].includes(rel))throw err(404,'ไม่พบหน้า');const file=path.join(root,'frontend',rel);res.writeHead(200,{'Content-Type':(mime[path.extname(file)]||'application/octet-stream')+'; charset=utf-8','Cache-Control':'no-store'});fs.createReadStream(file).pipe(res);
}catch(e){json(res,e.status||500,{error:e.status?e.message:'เกิดข้อผิดพลาดภายในระบบ'});if(!e.status)console.error(e)}}
if(process.argv[1]&&fileURLToPath(import.meta.url)===path.resolve(process.argv[1])){const port=Number(process.env.PORT||3000);http.createServer(handler).listen(port,()=>console.log(`Grab Driver Dashboard: ${origin}`))}
export { handler, db, analytics };
