import test from 'node:test';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import { Readable } from 'node:stream';
import { newDb } from 'pg-mem';
const mem=newDb({autoCreateForeignKeyIndices:true,noAstCoverageCheck:true}),adapter=mem.adapters.createPg();globalThis.__GRAB_TEST_POOL__=new adapter.Pool();process.env.DEMO_MODE='true';process.env.SESSION_SECRET='test-secret-at-least-32-characters-long';process.env.LINE_CHANNEL_SECRET='test-line-secret';const {handler}=await import('../backend/server.js'),{migrate,id}=await import('../backend/db.js');await migrate();const uid=id();await globalThis.__GRAB_TEST_POOL__.query('INSERT INTO users(id,email,name) VALUES($1,$2,$3)',[uid,'demo@local.test','Demo']);
async function call(url,method='GET',data,cookie=''){const req=Readable.from(data?[Buffer.from(JSON.stringify(data))]:[]);Object.assign(req,{url,method,headers:{cookie,origin:'http://localhost:3000',host:'localhost:3000'}});const res={headers:{},statusCode:200,setHeader(k,v){this.headers[k.toLowerCase()]=v},getHeader(k){return this.headers[k.toLowerCase()]},writeHead(status,headers={}){this.statusCode=status;Object.assign(this.headers,headers)},end(value){this.body=value||''}};await handler(req,res);return {status:res.statusCode,headers:res.headers,data:JSON.parse(res.body||'{}')}}
async function lineCall(payload){const raw=Buffer.from(JSON.stringify(payload)),req=Readable.from([raw]);Object.assign(req,{url:'/api/integrations/line/webhook',method:'POST',headers:{host:'localhost:3000','x-line-signature':crypto.createHmac('sha256',process.env.LINE_CHANNEL_SECRET).update(raw).digest('base64')}});const res={headers:{},statusCode:200,setHeader(k,v){this.headers[k.toLowerCase()]=v},getHeader(k){return this.headers[k.toLowerCase()]},writeHead(status,headers={}){this.statusCode=status;Object.assign(this.headers,headers)},end(value){this.body=value||''}};await handler(req,res);return {status:res.statusCode,data:JSON.parse(res.body||'{}')}}
test('API session, trip ledger, analytics, and linked deletion',async()=>{assert.equal((await call('/api/trips')).status,401);const login=await call('/api/auth/demo','POST');assert.equal(login.status,200);assert.match(login.headers['set-cookie'],/Max-Age=1900800/);const cookie=login.headers['set-cookie'].split(';')[0];const trip=await call('/api/trips','POST',{started_at:'2026-10-09T09:00+07:00',ended_at:'2026-10-09T09:40+07:00',gross_baht:'200.00',platform_fee_baht:'40.00',paid_km:8,deadhead_km:2,payment_method:'cash'},cookie);assert.equal(trip.status,201);const entries=(await call('/api/wallet','GET',null,cookie)).data;assert.equal(entries.length,2);assert.deepEqual(entries.map(x=>[x.wallet,x.amount_baht]).sort(),[['cash','200.00'],['credit','-40.00']]);const summary=(await call('/api/analytics?from=2026-10-09&to=2026-10-09','GET',null,cookie)).data;assert.equal(summary.tripCount,1);assert.equal(summary.revenueBaht,'160.00');assert.equal((await call('/api/trips/'+trip.data.id,'DELETE',null,cookie)).status,200);assert.equal((await call('/api/wallet','GET',null,cookie)).data.length,0)});
test('LINE account linking uses a one-time six-digit code and enforces one-to-one ownership',async()=>{const login=await call('/api/auth/demo','POST'),cookie=login.headers['set-cookie'].split(';')[0],issued=await call('/api/integrations/line/link','POST',{},cookie);assert.equal(issued.status,201);assert.match(issued.data.code,/^\d{6}$/);const stored=await globalThis.__GRAB_TEST_POOL__.query('SELECT code_hash FROM line_link_codes WHERE user_id=$1',[uid]);assert.notEqual(stored.rows[0].code_hash,issued.data.code);const event={events:[{webhookEventId:'link-event-1',type:'message',timestamp:Date.now(),source:{type:'user',userId:'U-line-one'},message:{id:'m1',type:'text',text:issued.data.code}}]};assert.equal((await lineCall(event)).status,200);assert.equal((await call('/api/integrations/line/link','GET',null,cookie)).data.linked,true);assert.equal((await globalThis.__GRAB_TEST_POOL__.query('SELECT COUNT(*)::int n FROM line_accounts WHERE user_id=$1',[uid])).rows[0].n,1);assert.equal((await globalThis.__GRAB_TEST_POOL__.query('SELECT COUNT(*)::int n FROM line_link_codes WHERE user_id=$1',[uid])).rows[0].n,0)});
test('Gemini image analysis creates a review draft that can become a fuel record',async()=>{const login=await call('/api/auth/demo','POST'),cookie=login.headers['set-cookie'].split(';')[0],previousFetch=globalThis.fetch;process.env.GEMINI_API_KEY='test-key';globalThis.fetch=async url=>{if(String(url).includes('generativelanguage.googleapis.com'))return new Response(JSON.stringify({candidates:[{content:{parts:[{text:JSON.stringify({document_type:'fuel',raw_text:'น้ำมัน 30 ลิตร 1200 บาท เลขไมล์ 54321',liters:30,total_baht:'1200.00',odometer_km:54321,station:'Test Station',confidence:0.98})}]}}]}),{status:200,headers:{'Content-Type':'application/json'}});return previousFetch(url)};try{const image='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',draft=await call('/api/ocr/drafts','POST',{image},cookie);assert.equal(draft.status,201);assert.equal(draft.data.parsed.document_type,'fuel');assert.equal(draft.data.parsed.ai_provider,'gemini');const confirmed=await call(`/api/ocr/drafts/${draft.data.id}/confirm`,'POST',{record_type:'fuel',filled_at:'2026-10-09T19:00+07:00',liters:30,total_baht:'1200.00',odometer_km:54321,station:'Test Station',note:'ตรวจจากภาพ'},cookie);assert.equal(confirmed.status,200);assert.equal(confirmed.data.total_baht,'1200.00')}finally{globalThis.fetch=previousFetch;delete process.env.GEMINI_API_KEY}});
